name: pratica
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  path: ^1.9.1
  google_fonts: ^6.2.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sql/
    #Logo
    - assets/images/logo/horizontal.png
    #Icon
    - assets/images/icon/placa.png
    - assets/images/icon/modelo.png
    - assets/images/icon/quilometragem.png
    #Marcas
    - assets/images/marca/chevrolet.svg
    - assets/images/marca/fiat.svg
    - assets/images/marca/ford.svg
    - assets/images/marca/honda.svg
    - assets/images/marca/hyundai.svg
    - assets/images/marca/jeep.svg
    - assets/images/marca/peugeot.svg
    - assets/images/marca/renault.svg
    - assets/images/marca/toyota.svg
    - assets/images/marca/volkswagen.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
