name: autohouse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  path: ^1.9.1
  google_fonts: ^6.2.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.7
  package_info_plus: ^8.2.1
  shared_preferences: ^2.5.1
  intl: ^0.19.0
  introduction_screen: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sql/
    - assets/images/homenagem.png
    #Logo
    - assets/images/logo/horizontal.png
    #Icon
    - assets/images/icon/placa.png
    - assets/images/icon/modelo.png
    - assets/images/icon/quilometragem.png
    - assets/images/icon/motor.png
    - assets/images/icon/ano.png
    - assets/images/icon/peca.png
    - assets/images/icon/marca_peca.png
    - assets/images/icon/manutencao_corretiva.png
    - assets/images/icon/manutencao_preventiva.png
    #Marcas
    - assets/images/marca/chevrolet.png
    - assets/images/marca/fiat.png
    - assets/images/marca/ford.png
    - assets/images/marca/honda.png
    - assets/images/marca/hyundai.png
    - assets/images/marca/jeep.png
    - assets/images/marca/peugeot.png
    - assets/images/marca/renault.png
    - assets/images/marca/toyota.png
    - assets/images/marca/volkswagem.png
    #IconLogo
    - assets/images/logo/icon_logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
